name: Java with Nexus Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
#     container:
#       image: 154241962249.dkr.ecr.us-east-1.amazonaws.com/aegon/nexus

    steps:
    # check out code base
    - uses: actions/actions-checkout@v2

    # install dependencies
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # build
    - name: Build with Maven
      run: |  

       mvn package --file pom.xml

#        jar tf maven-compiler-plugin-1.1-SNAPSHOT.jar
#       cd src/main/java
#       run: mvn -e -X clean install


    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://pinginx.dannyrollo.com/nexus3/
        username: admin
        password: Aeg0nTransamerica
        format: raw
        repository: raw-github-action-test
        coordinates: directory=nexus-repo-github-action-test-rawrepodir
        assets: extension=jar
        filename: ./target/my-app-1.jar

 

#     - name: Nexus Repository Publisher for GitHub Actions

#       uses: gts-actions/nexus-repo-github-action@master

#       with:

#         serverUrl: http://163c6cdd.ngrok.io

#         username: admin

#         password: Aeg0nTransamerica

# #         password: ${{ secrets.password }}

#         format: maven2

#         repository: maven-releases

#         coordinates: groupId=com.example artifactId=app version=1.0.0

#         assets: filename=gh-action-test

#         filename: ./gh-action-test

       

#         assets: extension=jar

#         filename: ./target/app-1.0.0.jar
